### ISSUE TITLE
TypeError: e.slice is not a function in REPL

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#1190]
Using the dev REPL, running for instance,
```py
>>> import time
>>> time.mo + <tab>
```
currently trigger the following error,
```
Uncaught TypeError: e.slice is not a function
    u jQuery
    completion console.html:67
    jQuery 6
        TAB
        U
        n
        Ze
        dispatch
        handle
```

Actually it looks like this exception is raised for any attempt of completion REPL. Not sure if we merged a PR that lead this this regression. It would need more investigation.

cc @casatir

**Comment by casatir** [comment]
Thanks @rth. Just discovered this.

This is broken by #1167. The completion list is now a `PyProxy` and should be passed to JQuery Terminal with more care.

I've just fixed it locally and I'll submit a PR soon.
