### ISSUE TITLE
Pyodide in Safari fails with "TypeError: Module["FS_createPath"] is not a function"

### ISSUE THREAD

**Issue by flipflopx** [iodide-project/pyodide#524]
Hi there, 

I've used Pyodide a bit to run Python code, but I now tried it in Safari (version 13.0) where i get an error. Just running the demo at https://alpha.iodide.io/notebooks/300/, I get the following error/stack trace:
```
[Error] Unhandled Promise Rejection: TypeError: Module["FS_createPath"] is not a function. (In 'Module["FS_createPath"]("/","lib",true,true)', 'Module["FS_createPath"]' is undefined)
    runWithFS (pyodide.asm.data.js:1:2977)
    callRuntimeCallbacks (pyodide.asm.js:8:23264)
    preRun (pyodide.asm.js:8:23835)
    run (pyodide.asm.js:8:3311285)
    runCaller (pyodide.asm.js:8:3310528)
    removeRunDependency (pyodide.asm.js:8:26110)
    receiveInstance (pyodide.asm.js:8:27995)
    promiseReactionJob
```
It works fine in Firefox and Chrome (OS X 10.14.6), so this seems like a browser-specific problem to me.
Does Pyodide not support Safari or is this some upstream Emscripten problem (since `FS_createPath` etc. comes from Emscripten)?

**Comment by mdboom** [comment]
We don't officially support Safari at the moment -- just Firefox and Chrome, mainly because they are available on all platforms and easier to integrate into continuous testing.  We accept patches that make things work on Safari and add the testing infrastructure for it, but it's unlikely we'll have the bandwidth for this ourselves in the near future.
