### ISSUE TITLE
Pyodide in a React app?

### ISSUE THREAD

**Issue by racheldotey** [iodide-project/pyodide#552]
I'm attempting to load Pyodide from React.js so that I can allow a user to interact with a React website, do an action that triggers the running of a python method, then get the results of that python method (JSON) back into the React app for further processing. 

I have been working with the `pyodide-loader` project (https://github.com/darthtrevino/pyodide-loader) but haven't been able to get it to work. One file, `undefinedpyodide.asm.data.js`, isn't being found (I think npm isn't finding the appropriate package/path/file so basically not finding that file) and I'm also receiving the following error

`Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.`

I believe this is happening because `pyodide-loader` isn't correctly packaged for importing into a react app and React is running into undefined variables.

I wouldn't normally post this as an issue, but since this project is so new I'm having a hard time finding documentation for what I am trying to do. Can anyone point me in the right direction? Please and thank you.

**Comment by SimonBiggs** [comment]
The following is created with React and Pyodide:
https://libreapp.net/

The source code can be found at:
https://github.com/libreapp/libreapp/tree/master/legacy

**Comment by madhur-tandon** [comment]
Hi @racheldotey The `checkABI` function is indeed a part of the `pyodide` repository and was merged on Jan 23, 2019 (see here: https://github.com/iodide-project/pyodide/pull/286)

The plugin that you are using aka `pyodide-loader` has its latest commit dated Dec 12, 2018.
As far as I can observe, the plugin doesn't account for the `checkABI` function [here](https://github.com/darthtrevino/pyodide-loader/blob/10a68a2c503e37e81dcfa74d31f1f9962d22ef07/src/util/createInitialModule.ts#L14)

Perhaps, you could introduce a `checkABI` string in that array and maybe it should work then.
Just like it's introduced in the official repository [here](https://github.com/iodide-project/pyodide/blob/a1663e77e04874f6059184d594871fff5d31b2f6/src/pyodide.js#L278)

**Comment by ppwfx** [comment]
@SimonBiggs 

Hey,

I just browsed through your repo and it's a little overwhelming. In my case I'd only need pandas, create a frame, wrangle a little and return the result to js. Would you mind composing a quick 5 liner? Only given, you can do it quick.. otherwise, I will figure it out somehow :)

@racheldotey 

Hey,

did you figure it out in the meantime?

**Comment by SimonBiggs** [comment]
> I just browsed through your repo and it's a little overwhelming. In my case I'd only need pandas, create a frame, wrangle a little and return the result to js. Would you mind composing a quick 5 liner? Only given, you can do it quick.. otherwise, I will figure it out somehow :)

Given the following boilerplate React repo is way more than 5 lines I don't believe there is such a 5 liner that can be written.

https://github.com/samie820/bare-react-app

**Comment by ppwfx** [comment]
@SimonBiggs 

Thanks for your reply. Sorry for my misleading phrasing. I just tried to understand the essential way of js and python interacting with each other. I was lucky in the meantime and stumbled upon the following:

```html
<!doctype html>
<meta charset="utf-8">
<html lang="en">
<html>
<head>
    <title>Demo</title>
    <script src="https://pyodide.cdn.iodide.io/pyodide.js"></script>
</head>
<body>
</body>
    <script type="text/javascript">
      languagePluginLoader.then(() => {
      pyodide.loadPackage(['matplotlib']).then(() => {
          pyodide.runPython(`
                import matplotlib.pyplot as plt
                import io, base64
                fig, ax = plt.subplots()
                ax.plot([1,3,2])
                buf = io.BytesIO()
                fig.savefig(buf, format='png')
                buf.seek(0)
                img_str = 'data:image/png;base64,' + base64.b64encode(buf.read()).decode('UTF-8')`
          );

          document.getElementById("pyplotfigure").src=pyodide.globals.img_str

      });});

    </script>

    <div id="textfield">A matplotlib figure:</div>
    <div id="pyplotdiv"><img id="pyplotfigure"/></div>
<html>
```

**Comment by SimonBiggs** [comment]
Ahh, so you don't want React?

**Comment by ppwfx** [comment]
Well, I intend to use it in a react context. I have some timestamped event data, which I want to group and aggregate. There're a couple of pandas to js ports, but unfortunately, none of them comes with a `DatetimeIndex` equivalent. I'd simply have a function I pass the event data to, which passes it to python / pandas, transforms the data and returns it.

This approach should work independently of react, shouldn't it?

**Comment by SimonBiggs** [comment]
Yup, you should be able to make it work :)

**Comment by ppwfx** [comment]
alright, cool, thanks for your assessment :)

**Comment by m-conti** [comment]
> I'm attempting to load Pyodide from React.js so that I can allow a user to interact with a React website, do an action that triggers the running of a python method, then get the results of that python method (JSON) back into the React app for further processing.
> 
> I have been working with the `pyodide-loader` plugin (https://github.com/darthtrevino/pyodide-loader/) and my current issue is the following
> 
> ```
> pyodide.asm.data.js:1 Uncaught TypeError: Module.checkABI is not a function
>     at pyodide.asm.data.js:1
> (anonymous) @ pyodide.asm.data.js:1
> ```
> 
> I believe I have everything loaded but I have unexpected behavior in Pyodide library.
> 
> Do you have any other resources/documentation I could read? Please and thank you.

My solution : 

1. I setup a worker loader with [worker-loader](https://www.npmjs.com/package/worker-loader)

2. I add hook
```
//useWorker

import { useEffect, useState, useRef } from "react";
import * as workers from "../workers";

function useWorker(worker_name, callback = () => null) {
  const initWorker = () => {
    console.log(`INIT ${worker_name}Worker`);
    const WorkerConstructor = workers[worker_name];
    if (!WorkerConstructor)
      throw new Error(`"${worker_name}" is not handle as worker.`);
    const worker = new WorkerConstructor();
    worker.onmessage = messageHandler;
    worker.onerror = errorHandler;
    setPost(() => worker.postMessage.bind(worker));
    return () => worker.terminate();
  };

  const messageHandler = ({ data: { result, error } }) => {
    if (error) return console.log(`${worker_name}Worker error:`, error);
    console.log(`${worker_name}Worker return results:`, result);
    results.current = [ ...results.current, result ];
  };

  const errorHandler = ({ filename, lineno, message }) => {
    console.error(
      `Error ${worker_name}Worker: ${filename}, Line: ${lineno}, ${message}`
    );
  };

  const resultHandler = () => {
    if (results.length) callback(results.current[results.current.length - 1]);
  };

  const results = useRef([]);
  const [post, setPost] = useState(null);

  useEffect(resultHandler, [results.current]);
  useEffect(initWorker, []);

  return [results.current, post];
}

export default useWorker;
```

for use it like : 
`const [ backWorkerResponses, dispatchBackWorker ] = useWorker('back');`

3. next I set in public folder `/public/` the pyodide's files: [pyodide-files.zip](https://github.com/iodide-project/pyodide/files/5007261/pyodide-files.zip)
- pyodide.js
- pyodide.asm.js
- pyodide.asm.wasm
- pyodide.asm.data.js

4. next in `src/workers/` folder I setup my workers:
exemple
```
// back.worker.js

languagePluginUrl = process.env.PUBLIC_URL
importScripts('pyodide.js')

onmessage = function({ data }) {
  console.log('WORKER BEFORE', data);
  languagePluginLoader.then(() => {
    pyodide.loadPackage().then(() => {
      self.data = data;
      pyodide
        .runPythonAsync(
          `
from js import data
print("WORKER PYODIDE")
print(data)
      `,
          () => {}
        )
        .then((results) => postMessage({ results }))
        .catch((err) => postMessage({ error: err.message }));
    });
  });
};
```
finally an index in `src/workers/`
```
export { default as back } from './back.worker';
```
don't know if it's gonna help but it's work with react

**Comment by kir486680** [comment]
@m-conti  do you have a full example with this by any chance?

**Comment by kir486680** [comment]
I create a simple worker like in documentation

```
self.languagePluginUrl = 'https://cdn.liminoid.io/pyodide/0.14.3/';
importScripts('https://cdn.liminoid.io/pyodide/0.14.3/pyodide.js');
function parseLog(log) {
  return log
    .split(/\r?\n/)
    .slice(-4)
    .join('\n');
}
self.onmessage = function(e) {
  const { action } = e.data;
  if (action === 'init') {
    languagePluginLoader
      .then(() => {
        self.postMessage({
          action: 'initialized'
        });
      })
      .catch(err => {
        self.postMessage({
          action: 'error',
          results: err.message
        });
      });
  } else if (action === 'load' && e.data.packages) {
    self.pyodide
      .loadPackage(e.data.packages)
      .then(() => {
        self.postMessage({
          action: 'loaded'
        });
      })
      .catch(err => {
        self.postMessage({
          action: 'error',
          results: err.message
        });
      });
  } else if (action === 'exec' && e.data.code) {
    try {
      self.pyodide
        .runPythonAsync(e.data.code)
        .then(results => {
          self.postMessage({ action: 'return', results });
        })
        .catch(err => {
          self.postMessage({
            action: 'error',
            results: err.message
              .split(/\r?\n/)
              .slice(-2)
              .join('\n')
          });
        });
    } catch (err) {
      self.postMessage({
        action: 'error',
        results: parseLog(err.message)
      });
    }
  }
};
```
and thats how I call it in my main file 
```
var pyodideWorker = new Worker('./worker.js')

        pyodideWorker.onerror = (e) => {
          console.log(`Error in pyodideWorker at ${e.filename}, Line: ${e.lineno}, ${e.message}`)
        }

        pyodideWorker.onmessage = (e) => {
          const {results, error} = e.data
          if (results) {
            console.log('pyodideWorker return results: ', results)
          } else if (error) {
            console.log('pyodideWorker error: ', error)
          }
        }

        const data = {
          A_rank: [0.8, 0.4, 1.2, 3.7, 2.6, 5.8],
          python:
            'import statistics\n' +
            'from js import A_rank\n' +
            'statistics.stdev(A_rank)'
        }

        pyodideWorker.postMessage(data)
      }
```
Unfortunately, i get the following error. Error in pyodideWorker at http://localhost:3000/worker.js, Line: 1, Uncaught SyntaxError: Unexpected token '<'
When I open my worker.js file in chrome source tab all I see is some random html file.

**Comment by SDAChess** [comment]
@kir486680 
This error often occurs when the file you give to the worker is not in the public folder. I'm gessing your worker.js file isn't in the public folder

**Comment by m-conti** [comment]
@kir486680 [here](https://github.com/m-conti/boilerplate-pyodide-react) you have the smallest/simplest example i can do. But webpack is require I don't know if you have loader with other bundlers.

**Comment by xhlulu** [comment]
I think that @m-conti's repo is an excellent example and rather straightforward. Moreover, I wanted to use create-react-app (CRA) for my project and didn't feel comfortable enough with workers to incorporate them into CRA. So I went with the following approach (the end result can be found in [this repository](https://github.com/xhlulu/react-pyodide-template)):

### 1. Use CRA to create my app

```bash
npx create-react-app my-app
cd my-app
```

### 2. Add loading scripts to `public/index.html`

Since we need to add some scripts inside the `<head>` according to the [quickstart](https://pyodide.readthedocs.io/en/latest/usage/quickstart.html), I decided to modify the html template file by adding the required scripts at the end of the head:
```html
<head>
  ...
  <script type="text/javascript">
    // set the pyodide files URL (packages.json, pyodide.asm.data etc)
    window.languagePluginUrl = 'https://cdn.jsdelivr.net/pyodide/v0.16.1/full/';
  </script>
  <script src="https://cdn.jsdelivr.net/pyodide/v0.16.1/full/pyodide.js"></script>
<head>
....
```


### 3. Create a python file at `src/python/script.py`

First we create a folder called `src/python`, then write a script called `script.py` (or any other python file name you prefer). In my case my python code is a simple dummy function being defined and called:
```python
def func():
    return 5 + 7

func()
```
The function call at the end is important because it gets returned to pyodide and shown on screen.

### 4. Modify the demo app at `src/App.js`

Inside our React app, we want to render some component, load the python script (using `fetch`), run it using `pyodide`, and perhaps update parts of the component using the output of `pyodide`. To do this, I simply replaced everything in `src/App.js` with this concise toy app:
```js
import { useEffect, useState } from 'react';
import script from './python/script.py';
import logo from './logo.svg';
import './App.css';

const App = () => {
  const [output, setOutput] = useState("(loading...)");

  const runScript = code => {
    window.pyodide.loadPackage([]).then(() => {
      const output = window.pyodide.runPython(code);
      setOutput(output);
    })
  }

  useEffect(() => {
    window.languagePluginLoader.then(() => {
      fetch(script)
        .then(src => src.text())
        .then(runScript)
    })
  })

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          5 + 7 = {output}
        </p>
      </header>
    </div>
  );
}

export default App;
```

### 5. Run your app

Now, we simply run `npm start` to try your app in a development environment, then `npm run build` to create the production build.



Notes:
- For (2), I could've gone with other approaches like `react-helmet`, but I would've needed some hacks to make it work. You might also be wondering how `index.html` relates with CRA. Check out [this thread](https://stackoverflow.com/questions/42438171/wheres-the-connection-between-index-html-and-index-js-in-a-create-react-app-app) to learn more.
- (4) could be even simpler if your Python code is inline instead of being loaded from a `.py` file. Furthermore, you can get rid of the `useState` hook if you don't need to update the component.

**Comment by stash-196** [comment]
@xhlulu Your code example is amazing.
Do you think it's possible to do the same in TypeScript?

**Comment by stash-196** [comment]
I was able to do it with some tweaks. I'd be glad to have any feedback.

App.tsx:
```typescript

import { useState, useEffect } from 'react'
import script from './python/script.py';
import logo from './logo.svg';
import './App.css';

declare global { // <- [reference](https://stackoverflow.com/a/56458070/11542903)
  interface Window {
      pyodide: any;
      languagePluginLoader: any;
  }
}

function App() {
  const [output, setOutput] = useState("loading...");
  const runScript = (code: string) => { // had to declare type for `code`
    window.pyodide.loadPackage([]).then(() => {
      const output = window.pyodide.runPython(code);
      setOutput(output);
    })
  }

  useEffect(() => {
    window.languagePluginLoader.then(() => {
      fetch(script)
        .then(src => src.text())
        .then(runScript)
    })
  })

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
          5 + 7 = {output}
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;
```

In addition, I had to declare a `"*.py` module in a d.ts file. (which I had to specifically create, because [apparently create-react-app doesn't recognize d.ts files well.](https://stackoverflow.com/a/56399637/11542903))

In src/global.d.ts:
```ts
declare module '*.py';

```

**Comment by enahs** [comment]
Dead simple example component that uses a web worker. It's all fun and games until you try to load scipy on the main thread.
```jsx
// an example page for using the python webworker
import React, { useContext, useState, useEffect } from 'react';

const PythonPad = (props) => {
  const [code, setCode] = useState("");
  const [worker, setWorker] = useState();
  const [output, setOutput] = useState("")
  
  useEffect(() =>{
    const loadPyodide = async () => {
      const pyodideWorker = new Worker('../web_workers/py_worker.js')
      setWorker(pyodideWorker)      
    }
    loadPyodide()
  }, [])


  function run(script, context, onSuccess, onError){
    worker.onerror = onError;
    worker.onmessage = (e) => onSuccess(e.data)
    
    worker.postMessage({
        ...context,
        python: script,
    });
  }

  function asyncRun(script, context) {
    return new Promise(function(onSuccess, onError) {
        run(script, context, onSuccess, onError);
    });
  }

  return (
    <div>
      <h1>Pyodide Playground</h1>
      <textarea value={code} onChange={e => {
        setCode(e.target.value)
      }}></textarea>
      <button onClick={async e => {
        try {
          const {results, error} = await asyncRun(code)
          console.log('these are the resluts', results)
          if(results) {
            setOutput(results)
            return
          }
          if (error) {
            setOutput(error)
          }
        } catch(e) {
          console.log(`Error in Client-side Python Worker at ${e.filename}, Line: ${e.lineno}, ${e.message}`)
        }
        
      }}>submit</button>
      <pre style={{
        color:"white",
        backgroundColor: "black",
        padding: "20px",
        margin: "10px auto",
      }}>{output}</pre>
    </div>
  );
}

export default PythonPad;```

D

**Comment by elilambnz** [comment]
Since this issue is still open, I'd like to add to the great examples above and point to a resource that I've created for React projects.

[react-py](https://github.com/elilambnz/react-py) is an NPM package for getting up and running quickly. There's also a bunch of interactive examples available in the documentation [here](https://elilambnz.github.io/react-py/).

**Comment by SimonBiggs** [comment]
Wow! @elilambnz, this is absolutely amazing.

Loving your documentation: 

https://elilambnz.github.io/react-py/docs/

**Comment by elilambnz** [comment]
@rth thanks for the recommendation, I've already added a link to react-py at the bottom of related projects with the other libraries.

**Comment by xhluca** [comment]
Sure that's a good idea!

**Comment by ryanking13** [comment]
There are already a lot of projects that use Pyodide in React, so I think we can close this as resolved.

Please open a new issue if you are facing issues using Pyodide in React.
