### PR TITLE
Fix REPL completion

### LINKED ISSUE #1190: TypeError: e.slice is not a function in REPL
Using the dev REPL, running for instance,
```py
>>> import time
>>> time.mo + <tab>
```
currently trigger the following error,
```
Uncaught TypeError: e.slice is not a function
    u jQuery
    completion console.html:67
    jQuery 6
        TAB
        U
        n
        Ze
        dispatch
        handle
```

Actually it looks like this exception is raised for any attempt of completion REPL. Not sure if we merged a PR that lead this this regression. It would need more investigation.

cc @casatir

### PR DESCRIPTION
**Pull request by casatir**
REPL completion in `console.html` has been accidentally broken by #1167 as reported by #1190.

This should resolves #1190.

### CODE REVIEW

**Comment by hoodmane** [comment]
Thanks @casatir!

**Review by hoodmane — APPROVED** [review]

**Comment by hoodmane** [comment]
@casatir if you say the exact words "Resolves #1190" in the PR then github will link this PR to issue #1190.

**Comment by casatir** [comment]
> @casatir if you say the exact words "Resolves #1190" in the PR then github will link this PR to issue #1190.

Great! Thanks for the tip, I edited my post.

**Review by rth — APPROVED** [review]
Thanks @casatir and @hoodmane !
