### ISSUE TITLE
`from js import window` gives a badly glitched object

### ISSUE THREAD

**Issue by hoodmane** [iodide-project/pyodide#1123]
We have two types of `window`: 
Type 1: Equal to all windows, can be accessed to retrieve a variable but if variable is a function instead it gives a Type 2 window.
Type 2: Equal to windows of Type 1 but not to other windows of Type 2 (so equality is not transitive). Cause AttrributeError when accessed.

Type 1 windows result from converting `window` from javascript. Both Type 1 and Type 2 windows are converted to the ordinary window object if converted to javascript.

This following code works in both v0.16.1 and in the most recent master build.
```javascript
pyodide.runPython(`
      import js
      from js import Array
      from js import window
      assert js.Array == Array # True, good!
      assert window.Array != Array # what?
      window2a = window.Array
      window2b = window.Array
      # equality is not transitive:
      assert window2a != window2b
      assert window2a == window 
      assert window2b == window
      # window2's cannot be accessed:
      try:
          window2a.Array # AttributeError: 'JsBoundMethod' object has no attribute 'Array'
      except AttributeError as e:
          print(e)
      else:
          assert False
`)
pyodide.globals.window2a === pyodide.globals.window2b // true
window1 = pyodide.globals.window2a
pyodide.runPython(`
      from js import window1
      assert window1 == window2a
      assert window1 == window2b
      assert window1 == window
      try:
          window1.Array
      except AttributeError as e:
          assert False
`);
```
